# This is the configuration file for a Dart server(DHCP & DNS & forwarding).
# For each interface, you can specify whether DHCP is enabled or not.
# While the DNS server is always enabled.

# This configuration contains 3 interfaces: ens32, ens37, ens33.
# ens33 is in cn. domain, ens32 is in sh.cn domain, ens37 is in sh.cn domain.
# This host serves as the DHCP & DNS server for the 2 domains: bj.cn and sh.cn.
# (and even the gateway for bj.cn and sh.cn, but this daemon does not do that)
# Domain cn is the parent domain of bj.cn and sh.cn.

# When a DHCP client in bj.cn or sh.cn applies for an IP address, this daemon will 
# answer it. And at the same time, the daemon will remember whether the client 
# supports Dart protocol or not. 

# If a DNS query packet arrives, this daemon will check whether the querier and 
# the queried party are in the same domain.
# If yes, it will return the IP address assigned by the DHCP service. 
# If not, it will return the IP address of this server's interface in the same domain.
# In other words, this server will forward packets between different domains. 
# (This will be handled by another forwarding program.)

interfaces:
  - name: ens37
    direction: uplink # uplink有且仅有一个。uplink接口同时作为默认路由出口，所有未成功匹配downlink接口的报文从此接口转发。
    domain: cn
    gateway: 192.168.2.2
    dns_servers:
      - 192.168.2.80

  - name: ens38
    direction: downlink
    address_pool: 10.100.0.100-10.100.0.199
    domain: sh.cn
    gateway: 10.100.0.1
    dns_servers:
      - 10.100.0.1
    static_bindings:
      - mac: "00:0c:29:f1:65:17"
        ip: "10.0.0.99"
